Online_Shop/src/java/addhandler/SubCategoryMB.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package addhandler;

import dao.AddDao;
import dao.ListDao;
import entity.Category;
import entity.SubCat;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;

/**
 *
 * @author John
 */
@ManagedBean
@SessionScoped

public class SubCategoryMB {
    SubCat subcat = new SubCat();
    String catname;
    List<Category> listCat;

    public List<Category> getListCat() {
        return listCat;
    }

    public void setListCat(List<Category> listCat) {
        this.listCat = listCat;
    }
    

    public SubCat getSubcat() {
        return subcat;
    }

    public void setSubcat(SubCat subcat) {
        this.subcat = subcat;
    }

    public String getCatname() {
        return catname;
    }

    public void setCatname(String catname) {
        this.catname = catname;
    }
    public String addSubCategory(){
        listCat = new ListDao().catListByName(catname);
        subcat.setSubCatId(listCat.get(0).getCatId());
        subcat.setSubCatName(subcat.getSubCatName());
        subcat.setSubCatDesc(subcat.getSubCatDesc());
        boolean status = new AddDao().addSubCatagory(subcat);
        if(status){
            FacesContext.getCurrentInstance().addMessage(null, new
               FacesMessage(FacesMessage.SEVERITY_INFO, "Data Saved", ""));
        }else{
             FacesContext.getCurrentInstance().addMessage(null, new
               FacesMessage(FacesMessage.SEVERITY_ERROR, "Data Not Saved", ""));
        }
      return null;  
    }
    
    public List<SelectItem> getCategoryName(){
        List<SelectItem> catname = new ListDao().catList();
        return catname;
    }
}

Online_Shop/web/addsubcat.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Hibernate Project</title>
    </h:head>
    <h:body>
        <h:form>
            <p:messages id="msg" closable="true" showDetail="true"></p:messages>
            <p:panelGrid columns="2"> 
                <h:outputLabel value="Category Name"></h:outputLabel>
                <p:selectOneMenu value="Select Category Name">
                    <f:selectItems value="#{subCategoryMB.categoryName}">
                    </f:selectItems>
                    
                </p:selectOneMenu> 
                
                <h:outputLabel value="SubCategory Name"></h:outputLabel>
                <h:inputText value="#{subCategoryMB.subcat.subCatName}"></h:inputText>
                
                <h:outputLabel value="SubCategory Description"></h:outputLabel>
                <h:inputText value="#{subCategoryMB.subcat.subCatDesc}"></h:inputText>
                
                <p:commandButton action="#{subCategoryMB.addSubCategory()}" value="save" update="msg"></p:commandButton>    
            </p:panelGrid>
            
        </h:form>
    </h:body>
</html>

Online_Shop/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html >
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <title>Hibernate Project</title>
    </h:head>
    <h:body>
        <h:form>
            <p:messages id="msg" closable="true" showDetail="true"></p:messages>
            <p:panelGrid columns="2"> 
                <h:outputLabel value="Category Name"></h:outputLabel>
                  <h:inputText value="#{categoryMB.category.catName}"></h:inputText>
                <h:outputLabel value="Category Description"></h:outputLabel>
                  <h:inputText value="#{categoryMB.category.catDesc}"></h:inputText>
                  <p:commandButton action="#{categoryMB.addCategory()}" value="save" update="msg"></p:commandButton>    
            </p:panelGrid>
            
        </h:form>
    </h:body>
</html>